apiVersion: v1
data:
  app.conf: |
    appname = PrometheusAlert
    #监听端口
    httpport = 8080
    runmode = dev
    #开启JSON请求
    copyrequestbody = true
    #webhook告警类型0 dingding,1 weixin
    webhook_type=0
    #钉钉机器人地址
    ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #企业微信机器人地址
    wxurl=https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #告警消息标题
    title=AlertCenter
    #链接到告警平台地址
    alerturl=http://prometheus.io
    #logo图标地址
    logourl=https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/logo.png
    #短信接口key
    appkey=e71xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #短信模版ID
    tpl_id=xxxxxx
    #短信sdk app id
    sdkappid=xxxxxxxxx
    #短信告警级别(等于3就进行短信告警) 告警级别定义 0 信息,1 警告,2 一般严重,3 严重,4 灾难
    messagelevel=3
    #电话接口key
    phonecallappkey=xxxxxxxxxxxxxxxxxxxxxx
    #电话模版ID
    phonecalltpl_id=xxxxxxxxx
    #电话sdk app id
    phonecallsdkappid=xxxxxxxxxx
    #电话告警级别(等于4就进行语音告警) 告警级别定义 0 信息,1 警告,2 一般严重,3 严重,4 灾难
    phonecalllevel=4
    #默认拨打号码
    #defaultphone=
    #未使用user.csv或者user.csv中的号码轮询结束备用号码
    backupphone=xxxxxxxxxxx
kind: ConfigMap
metadata:
  name: prometheus-alert-center-conf
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: prometheus-alert-center
    alertname: prometheus-alert-center
  name: prometheus-alert-center
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-alert-center
      alertname: prometheus-alert-center
  template:
    metadata:
      labels:
        app: prometheus-alert-center
        alertname: prometheus-alert-center
    spec:
      containers:
      - image: feiyu563/prometheus-alert
        name: prometheus-alert-center
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: prometheus-alert-center-conf-map
          mountPath: /app/conf/app.conf
          subPath: app.conf
      volumes:
      - name: prometheus-alert-center-conf-map
        configMap:
          name: prometheus-alert-center-conf
          items:
          - key: app.conf
            path: app.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    alertname: prometheus-alert-center
  name: prometheus-alert-center
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: prometheus-alert-center
